[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configurações PWA para Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "no-cache"

# Headers para manifesto PWA
[[headers]]
  for = "/manifest-totem.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# Headers para ícones PWA
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuração SPA - todas as rotas redirecionam para index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirecionar para modo totem
[[redirects]]
  from = "/totem"
  to = "/totem.html"
  status = 200

# Otimizações de performance
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
  canonical_urls = true 